resolver: lts-8.2
compiler-check: match-minor
compiler: ghc-8.0.2
require-stack-version: ">= 1.0.0"

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
